apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summarizer-api
  template:
    metadata:
      labels:
        app: summarizer-api
    spec:
      containers:
      - name: summarizer-container
        image: yourdockerhubusername/summarizer-api:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
