apiVersion: v1
kind: Service
metadata:
  name: summarizer-api-service
spec:
  type: LoadBalancer
  selector:
    app: summarizer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
